/**
 * Sync achievement requirement predicates. All receive (merged, hour); only `code_night` uses hour.
 */
const SYNC_ACHIEVEMENT_CHECKS = {
  complete_1_module: (m) => m.completedModules >= 1,
  complete_3_modules: (m) => m.completedModules >= 3,
  complete_5_modules: (m) => m.completedModules >= 5,
  complete_10_modules: (m) => m.completedModules >= 10,
  complete_15_modules: (m) => m.completedModules >= 15,
  complete_20_modules: (m) => m.completedModules >= 20,
  points_100: (m) => m.totalPoints >= 100,
  points_250: (m) => m.totalPoints >= 250,
  points_500: (m) => m.totalPoints >= 500,
  points_750: (m) => m.totalPoints >= 750,
  points_1000: (m) => m.totalPoints >= 1000,
  points_1500: (m) => m.totalPoints >= 1500,
  edit_1_time: (m) => m.totalEdits >= 1,
  edit_10_times: (m) => m.totalEdits >= 10,
  edit_50_times: (m) => m.totalEdits >= 50,
  edit_100_times: (m) => m.totalEdits >= 100,
  streak_5: (m) => m.streak >= 5,
  streak_10: (m) => m.streak >= 10,
  session_10_min: (m) => m.sessionTime >= 10,
  session_30_min: (m) => m.sessionTime >= 30,
  session_60_min: (m) => m.sessionTime >= 60,
  run_10_times: (m) => m.totalRuns >= 10,
  run_25_times: (m) => m.totalRuns >= 25,
  run_50_times: (m) => m.totalRuns >= 50,
  save_5_times: (m) => m.saveCount >= 5,
  code_night: (m, hour) => hour >= 0 && hour < 6 && m.totalEdits > 0,
  debug_session: (m) => m.debugSession,
  ai_companion_first_use: (m) => m.aiCompanionUses >= 1,
  ai_hint_3: (m) => m.aiHintRequests >= 3,
  ai_companion_10_uses: (m) => m.aiCompanionUses >= 10,
  ai_companion_25_uses: (m) => m.aiCompanionUses >= 25,
  ai_hint_10: (m) => m.aiHintRequests >= 10,
  ai_hint_25: (m) => m.aiHintRequests >= 25,
  ai_explain_code_once: (m) => m.aiExplainCodeUses >= 1,
  ai_explain_code_5: (m) => m.aiExplainCodeUses >= 5,
  ai_explain_error_once: (m) => m.aiExplainErrorUses >= 1,
  ai_explain_error_5: (m) => m.aiExplainErrorUses >= 5,
};

module.exports = { SYNC_ACHIEVEMENT_CHECKS };
