const mongoose = require("mongoose");

const moduleSchema = new mongoose.Schema(
  {
    // ── Core identity ────────────────────────────────────────────────────────
    title: { type: String, required: true, trim: true },
    description: { type: String, required: true, trim: true },

    // ── Classification ───────────────────────────────────────────────────────
    difficulty: {
      type: String,
      enum: ["beginner", "intermediate", "advanced"],
      default: "beginner",
    },
    category: {
      type: String,
      enum: [
        "javascript-basics",
        "game-development",
        "react-game-dev",
        "multiplayer",
        "advanced-concepts",
      ],
      required: true,
    },
    /**
     * 'vanilla'  – HTML / CSS / JS panels (default)
     * 'react'    – JSX / CSS panels only (React sandbox)
     */
    moduleType: {
      type: String,
      enum: ["vanilla", "react"],
      default: "vanilla",
    },
    /** Display order within its category (lower = earlier) */
    order: { type: Number, default: 0 },
    /** Rough expected time to complete in minutes */
    estimatedMinutes: { type: Number, default: 15 },
    /** Free-form tags for search / filtering */
    tags: [{ type: String }],

    // ── Learning content ─────────────────────────────────────────────────────
    /** Markdown body the student reads before coding */
    content: { type: String, required: true },
    /** High-level learning goals shown in the UI */
    objectives: [{ type: String }],

    // ── Code editor ──────────────────────────────────────────────────────────
    /**
     * Starter code loaded into the editor panels.
     * Intentionally incomplete — students finish it by following the steps.
     * Defaults are minimal; AI overwrites these on first load.
     */
    starterCode: {
      html: {
        type: String,
        default: '<!DOCTYPE html>\n<html>\n<head><title>Lesson</title></head>\n<body>\n  <h1>Open the console</h1>\n</body>\n</html>',
      },
      css: {
        type: String,
        default: 'body { font-family: Arial, sans-serif; padding: 24px; background: #f4f6fb; }',
      },
      javascript: {
        type: String,
        default: 'console.log("Ready! Add your code below.");\n',
      },
      /** Only populated for react moduleType */
      jsx: { type: String, default: "" },
    },

    // ── AI-generated step content ─────────────────────────────────────────────
    /**
     * 4-5 small, verifiable steps the student works through.
     * Generated by AI from content + objectives on first load.
     *
     * verifyType:
     *   'code'          – student wrote/changed something in the editor (default)
     *   'checkConsole'  – student must run code and check console output
     *   'checkComments' – student must add comments to the code
     */
    steps: [
      {
        title: { type: String, required: true },
        instruction: { type: String, default: "" },
        concept: { type: String, default: "" },
        verifyType: {
          type: String,
          enum: ["code", "checkConsole", "checkComments"],
          default: "code",
        },
        /**
         * Used when verifyType is 'checkConsole'.
         * Examples: { type: 'any' } | { exactLine: 'hello' } | { type: 'multipleLines' }
         */
        expectedConsole: { type: mongoose.Schema.Types.Mixed, default: null },
      },
    ],
    /** Short nudge hints shown in the sidebar. AI-generated. */
    hints: [{ type: String }],

    /** True once steps / hints / starterCode have been AI-generated and saved */
    contentGenerated: { type: Boolean, default: false },
  },
  { timestamps: true },
);

// Compound index: fast category + order queries used by getAll()
moduleSchema.index({ category: 1, order: 1 });

module.exports = mongoose.model("Module", moduleSchema);
